
#' Calculates karyotype heterogeneity and aneuploidy from the result CNVs 
#' 
#' The aneuploidy score is defined as the mean deviation from the base state across all cells and bins.
#' The heterogeneity score is defined as in the package Aneufinder (see Baker et al, Genome Biology 2016).
#' 
#' @param res_table Result data frame generated by the epiAneufinder main function
#' @param base_state Numeric encoding of base state (default 1)
#' @param plot_path Path to save a scatter plot of chromosome aneuploidy vs heterogeneity, 
#'                  only done if plot_path is not NULL (default NULL)
#' @param plot_width Width of the plot
#' @param plot_height Height of the plot
#' @return Aneuploidy and heterogeneity genome-wide and per chromosome
#' @import data.table
#' @import ggplot2
#' @export
karyotype_measures<-function(res_table, base_state=1, 
                             plot_path=NULL,plot_width=5,plot_height=4){
  
  #Convert it to a data.table (in case it's a data frame)
  res_table<-as.data.table(res_table)
  
  #Extract the cell names
  res_matrix<-res_table[,.SD,.SDcols = patterns("cell")]
  
  #Genomewide aneuploidy
  aneu_genome<-mean(res_matrix!=base_state)
  
  #Per chromosome aneuploidy
  aneu_chr<-sapply(unique(res_table$seq), function(chr){
    mean(res_matrix[res_table$seq == chr] != base_state)
  })
  
  #Per bin heterogeneity
  n_cell<-ncol(res_matrix)
  heterogen_bin<-apply(res_matrix,1,function(x){
    occ<-sort(table(x), decreasing = TRUE)
    return(sum(occ*0:(length(occ)-1))/n_cell)
  })
  
  #Per chromosome aneuploidy
  het_chr<-sapply(unique(res_table$seq), function(chr){
    mean(heterogen_bin[res_table$seq == chr])
  })
  
  metrics<-list()
  metrics[["genomewide"]]<-data.frame("Aneuploidy"=aneu_genome,
                                      "Heterogeneity"=mean(heterogen_bin))
  metrics[["per_chromosome"]]<-data.frame("Aneuploidy"=aneu_chr,
                                          "Heterogeneity"=het_chr)
  
  if(! is.null(plot_path)){
    plot_df<-metrics$per_chromosome
    plot_df$chrom<-rownames(plot_df)
    
    g<-ggplot(plot_df,aes(x=Aneuploidy,y=Heterogeneity,label=chrom))+
      geom_point()+geom_text(hjust=1,vjust=0)+
      theme_bw()+
      xlab("Aneuploidy per chromosome")+
      ylab("Heterogeneity per chromosome")
    
    ggsave(g, file=plot_path,width=plot_width,height=plot_height)
  }
  
  return(metrics)
}

#' Calculates CNV burden per cell
#' 
#' The CNV burden (=aneuploidy score) per cell is calculated as 
#' the mean deviation from the base state across all bins 
#' 
#' @param res_table Result data frame generated by the epiAneufinder main function
#' @param base_state Numeric encoding of base state (default 1)
#' @return Aneuploidy (=CNV burden) per cell as a named vector
#' @import data.table
#' @export
cnv_burden_per_cell<-function(res_table,base_state=1){
  
  #Convert it to a data.table (in case it's a data frame)
  res_table<-as.data.table(res_table)
  
  #Extract the cell names
  res_matrix<-res_table[,.SD,.SDcols = patterns("cell")]
  
  #Calculate aneuploidy per cell
  aneu_cell<-apply(res_matrix,2,function(x){
    mean(x!=base_state)})
  
  return(aneu_cell)
}
  