
#' Calculates karyotype heterogeneity and aneuploidy from the result CNVs 
#' 
#' The aneuploidy score is defined as the mean deviation from the base state across all cells and bins.
#' The heterogeneity score is defined as in the package Aneufinder (see Baker et al, Genome Biology 2016).
#' 
#' @param res_table Result data frame generated by the epiAneufinder main function
#' @param base_state Numeric encoding of base state (usually 1)
#' @return Aneuploidy and heterogeneity genome-wide and per chromosome
#' @export
karyotype_measures<-function(res_table, base_state=1){
  
  #Convert it to a data.table (in case it's a data frame)
  res_table<-as.data.table(res_table)
  
  #Extract the cell names
  res_matrix<-res_table[,.SD,.SDcols = patterns("cell")]
  
  #Genomewide aneuploidy
  aneu_genome<-mean(res_matrix!=base_state)
  
  #Per chromosome aneuploidy
  aneu_chr<-sapply(unique(res_table$seq), function(chr){
    mean(res_matrix[res_table$seq == chr] != base_state)
  })
  
  #Per bin heterogeneity
  n_cell<-ncol(res_matrix)
  heterogen_bin<-apply(res_matrix,1,function(x){
    occ<-sort(table(x), decreasing = TRUE)
    return(sum(occ*0:(length(occ)-1))/n_cell)
  })
  
  #Per chromosome aneuploidy
  het_chr<-sapply(unique(res_table$seq), function(chr){
    mean(heterogen_bin[res_table$seq == chr])
  })
  
  metrics<-list()
  metrics[["genomewide"]]<-data.frame("Aneuploidy"=aneu_genome,
                                      "Heterogeneity"=mean(heterogen_bin))
  metrics[["per_chromosome"]]<-data.frame("Aneuploidy"=aneu_chr,
                                          "Heterogeneity"=het_chr)
  
  return(metrics)
}
